Weather forecast request
yarostbaklajana/WeatherApp pull request #6
Opened 2017-03-25 17:40 UTC by yarostbaklajana

The purpose of this pull request is :
-to make request to OpenWeatherMap site 
-to handle response 
-to create array with forecast cards for 3-day period
-to print to console array with forecast cards

2017-03-26 16:39 UTC, DarkXaHTeP requested changes

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +    async getForecasts(cityID) {
It is rather forecast than forecasts

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +    async handleSubmit(cityID) {
Use camelCase for arguments names everywhere in the code. "ID" is NOT an abbreviation

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +            const threeDayForecastList = fiveDayForecast.data.list.slice(0, 21);
21 (items in your list for three days) x 3 (new item in list every three hours) = 63 (hours of forecast)
63 / 3 (days required) = 21 (amounts of hours in your imaginary day)

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +        let forecastCards = [];
Why not const?

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +                weatherIconId: singleForecast.weather[0].id,
Why don't you insert complete icon URL for convenience? This icon id is useless without whole URL anyway

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +        return hpa * 0,75;
will always return 0

2017-03-26 16:39 UTC, DarkXaHTeP commented on src/components/app.jsx
> +        if (directionInDeg >= 337.2 && directionInDeg <= 22.5) {
Why 337.2?

2017-03-26 17:02 UTC, yarostbaklajana commented on src/components/app.jsx
> +        if (directionInDeg >= 337.2 && directionInDeg <= 22.5) {
It's misprint

2017-03-26 18:27 UTC, DarkXaHTeP requested changes

2017-03-26 18:27 UTC, DarkXaHTeP commented on src/components/app.jsx
> +            const threeDayForecastList = fiveDayForecast.data.list.slice(0, 25);
Make sure that date-time is in Ukrainian local time and adjust number of cards to not exceed three days

2017-03-26 18:27 UTC, DarkXaHTeP commented on src/components/app.jsx
>                  temperature: singleForecast.main.temp,
`temperature: -2.68` as far as I can see on the screenshot provided in App description, the format of the temperature is different

2017-03-26 18:27 UTC, DarkXaHTeP commented on src/components/app.jsx
> +        return (hPa * 0.75).toFixed(0);
Use Math.round

2017-03-28 05:36 UTC, DarkXaHTeP approved these changes

2017-03-28 05:36 UTC, merged